[package]
name = "coding_game_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
